### ISSUE TITLE
BTC private key to address and balance check

### ISSUE THREAD

**Issue by Handsomekaizer** [vergl4s/ethereum-mnemonic-utils#7]
I just stumbled on these your GitHub repo I was looking for a program that will help me convert my compressed Bitcoin private key to address and check the balance. Could you please help me update or create a python program that will help me convert my compressed private key to address and check the balance. The reason I needed this was to scan through a massive private key txt file and see if I can find my missing 6 characters private key. Please help me if I recover the wallet I will donate some BTC to you. Thanks

**Comment by AdamT20054** [comment]
I'm not the repo owner, but if he doesn't want to help you, feel free to let me know and I'd be happy to help - I've got an old BTC mnemonic checker I can change for you :) @Handsomekaizer

**Comment by Handsomekaizer** [comment]
> I'm not the repo owner, but if he doesn't want to help you, feel free to let me know and I'd be happy to help - I've got an old BTC mnemonic checker I can change for you :) @Handsomekaizer

Please do

**Comment by vergl4s** [comment]
Ok boys this isn't "scammer matchmaking", go do this shit somewhere else.

**Comment by AdamT20054** [comment]
> > I'm not the repo owner, but if he doesn't want to help you, feel free to let me know and I'd be happy to help - I've got an old BTC mnemonic checker I can change for you :) @Handsomekaizer
> 
> Please do

I'll throw it together when I get some free time :)

**Comment by AdamT20054** [comment]
> Ok boys this isn't "scammer matchmaking", go do this shit somewhere else.

It's open source. Just check it if you think it's suspect.
