### ISSUE TITLE
AttributeError: 'mpz' object has no attribute 'to_bytes'

### ISSUE THREAD

**Issue by zjor** [vergl4s/ethereum-mnemonic-utils#8]
Hello, I'm having a problem converting the seed phrase to a private key:

```
Traceback (most recent call last):
  File "mnemonic_utils.py", line 162, in <module>
    private_key = mnemonic_to_private_key(mnemonic)
  File "mnemonic_utils.py", line 147, in mnemonic_to_private_key
    private_key, chain_code = derive_bip32childkey(private_key, chain_code, i)
  File "mnemonic_utils.py", line 66, in derive_bip32childkey
    key = key.to_bytes(32, byteorder='big')
AttributeError: 'mpz' object has no attribute 'to_bytes'
```
Python 3.8.3
base58==2.1.1
ecdsa==0.18.0

Mac OS: 12.6.2

Any help appreciated

**Comment by vergl4s** [comment]
Hy @zjor. It appears you are using the "mpz -- GNU arbitrary magnitude integers" module which seems to breaking the way integers are used. Just a hunch.

I did a quick debug and my 'key' variable on like 66 are always of type 'int' but yours seem to be an 'mpz' object.

I'd suggest try spinning a fresh environment using venv or something like that and give it another go. Let me know how it goes
